[build]

  command = "npm run build"  # Replace with your build command

  publish = "build"  # Replace with your build output directory

[build.environment]

  NODE_VERSION = "14"  # Specify the desired Node.js version

[[redirects]]

  from = "/*"

  to = "/index.html"

  status = 200

